// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderProcessingAPI.Infrastructure.Data;


#nullable disable

namespace OrderProcessingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623232545_AddOrdersSeed")]
    partial class AddOrdersSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderProcessingAPI.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ana Silva",
                            OrderNumber = "PED-0001",
                            Status = 0,
                            TotalAmount = 250.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 10, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Carlos Souza",
                            OrderNumber = "PED-0002",
                            Status = 1,
                            TotalAmount = 1340.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 20, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fernanda Lima",
                            OrderNumber = "PED-0003",
                            Status = 4,
                            TotalAmount = 89.90m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ricardo Mendes",
                            OrderNumber = "PED-0004",
                            Status = 5,
                            TotalAmount = 499.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 40, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Juliana Costa",
                            OrderNumber = "PED-0005",
                            Status = 6,
                            TotalAmount = 720.50m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 40, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
