// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderProcessingAPI.Infrastructure.Data;

#nullable disable

namespace OrderProcessingAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderProcessingAPI.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03d7c953-166b-4005-aebd-9b7452f7895c"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ana Silva",
                            OrderNumber = "PED-0001",
                            Status = 0,
                            TotalAmount = 250.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fa10850e-3be4-46b6-9b94-16289600b049"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 10, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Carlos Souza",
                            OrderNumber = "PED-0002",
                            Status = 2,
                            TotalAmount = 1340.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5951a1b8-e09a-465c-8635-e633c7f8d15a"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 20, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Fernanda Lima",
                            OrderNumber = "PED-0003",
                            Status = 4,
                            TotalAmount = 89.90m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2ac64cde-d27a-47d2-9f12-f3d0fb8ff35c"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Ricardo Mendes",
                            OrderNumber = "PED-0004",
                            Status = 5,
                            TotalAmount = 499.00m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e8d80e2a-15f6-4902-ab16-ddf48b4137e0"),
                            CreatedAt = new DateTime(2026, 6, 20, 12, 40, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Juliana Costa",
                            OrderNumber = "PED-0005",
                            Status = 6,
                            TotalAmount = 720.50m,
                            UpdatedAt = new DateTime(2026, 6, 20, 12, 40, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
